let myAge = 21;
let earlyYears = 2;
earlyYears*= 10.5;
//myAge-= 2;
let laterYears = myAge;
laterYears*=4;
console.log(earlyYears,laterYears);
myAgeInDogYears = earlyYears + laterYears;
myName = "Yash Pradhan".toLowerCase();
console.log(`My name is ${myName}. I am ${myAge} years old in human years which is ${myAgeInDogYears} years old in dog years`);
